# Для начала указываем исходный образ, он будет использован как основа
FROM mongo:latest
# Необязательная строка с указанием автора образа
MAINTAINER vyalov.alexander@gmail.com

COPY ./docker/mongo/docker-command.sh /docker-command.sh